In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

clf1 = LogisticRegression(multi_class='ovr', solver='liblinear')
clf1.fit(X_train, y_train)
pred1 = clf1.predict(X_test)

print("\nMulticlass Classification Results:")
print("Confusion Matrix:\n", confusion_matrix(y_test, pred1))
print("\nClassification Report:\n", classification_report(y_test, pred1))
print("\nAccuracy:", accuracy_score(y_test, pred1))

clf2 = LogisticRegression(max_iter=200)
clf2.fit(X_train, y_train)
pred2 = clf2.predict(X_test)

print(f'\nAccuracy: {accuracy_score(y_test, pred2):.2f}')
print('Classification Report:\n', classification_report(y_test, pred2))
print('Confusion Matrix:\n', confusion_matrix(y_test, pred2))



Multiclass Classification Results:
Confusion Matrix:
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30


Accuracy: 0.9666666666666667

Accuracy: 1.00
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 

c:\Users\yuvra\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
